version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: frontend_proxy
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - dev

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    networks:
      - dev

  frontend:
    build:
      context: . # Указываем текущую директорию как контекст сборки
      dockerfile: Dockerfile
    container_name: nuxt-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=https://awesomekyrgyztravel.com/api/v1
    networks:
      - dev

networks:
  dev:
    name: dev